name: RAKBANK_CICD


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  Ant_build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant1
        run: ant -noinput -buildfile build.xml

  SonarQubeTrigger:
     name: SonarQube_Scanner
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@master
     - name: SonarQube_Scan
       uses: kitabisa/sonarqube-action@master
       with:
          host: ${{ secrets.SONAR_HOST }}
          login: ${{ secrets.SONAR_TOKEN}}
          projectBaseDir: "Application1"
          projectKey: "Devops_RakCICD"
          projectName: "Devops_RakCICD"
          projectVersion: "v0.0.1"
          
  BarFile_Deploy_in_Openshift:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v2
     - name: docker login
       env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        OC_USERNAME: ${{secrets.OC_USERNAME}}
        OC_PASSWORD: ${{secrets.OC_PASSWORD}}
       run: |
         docker login -u manojreddyeidiko -p Ashwanth@8801
     - name: Build the Docker image1
       run: docker build -t cp4i:v1 --file Dockerfile .
            docker tag cp4i:vi manojreddyeidiko/cp4i
     - name: oc login,oc project,Docker tag &push
       run: |
        /usr/local/bin/ && ./oc login -u $OC_USERNAME -p $OC_PASSWORD --insecure-skip-tls-verify=true
        /usr/local/bin/ && ./oc project manoj
        /usr/local/bin/oc new-app --docker-image=manojreddyeidiko/cp4i:latest -e LICENSE=accept 
        /usr/local/bin/oc create route passthrough devopsimage --service=devopsimage --port=7843


          
        
